# Generated by Django 5.0.14 on 2026-07-16 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nida_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='NIDA must be in the format YYYYMMDD-XXXXX-XXXXX-XX and cannot start with 0 (e.g., 19501007-11101-00001-26)', regex='^[1-9]\\d{7}-\\d{5}-\\d{5}-\\d{2}$')]),
        ),
    ]
