# Generated by Django 5.0.14 on 2026-09-17 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='tin',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='TIN must be exactly 9 digits and cannot start with 0.', regex='^[1-9]\\d{8}$')]),
        ),
    ]
