# Generated by Django 5.0.14 on 2026-09-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_individual_tin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='date_registered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
