# Generated by Django 5.0.14 on 2026-08-15 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='tin',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='TIN must be exactly 9 digits and cannot start with 0.', regex='^[1-9]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tin',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='TIN must be exactly 9 digits and cannot start with 0.', regex='^[1-9]\\d{8}$')]),
        ),
    ]
