# Generated by Django 5.0.14 on 2026-09-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_date_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationrepresentative',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organizationrepresentative',
            name='identity_number',
        ),
        migrations.RemoveField(
            model_name='organizationrepresentative',
            name='identity_type',
        ),
        migrations.RemoveField(
            model_name='organizationrepresentative',
            name='phone',
        ),
    ]
