# Generated by Django 5.0.14 on 2026-09-17 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_organizationrepresentative_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantcontact',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='applicantcontact',
            name='contact_value',
        ),
        migrations.RemoveField(
            model_name='applicantcontact',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='applicantcontact',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantcontact',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='applicantcontact',
            name='landline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Landline'),
        ),
        migrations.AddField(
            model_name='applicantcontact',
            name='mobile_phone',
            field=models.CharField(default='', max_length=50, verbose_name='Mobile Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicantcontact',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='users.applicant'),
        ),
    ]
