# Generated by Django 5.0.14 on 2026-09-17 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_applicantcontact_contact_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantaddress',
            name='residency_duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Residency Duration / Muda wa Kuishi Mahali Hapo'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='tin',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='TIN must be exactly 9 digits and cannot start with 0.', regex='^[1-9]\\d{2}-?\\d{3}-?\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tin',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='TIN must be exactly 9 digits and cannot start with 0.', regex='^[1-9]\\d{2}-?\\d{3}-?\\d{3}$')]),
        ),
    ]
