# Generated by Django 5.0.14 on 2026-09-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_companyprofile_country_companyprofile_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
