# Generated by Django 5.0.14 on 2026-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_companyprofile_district_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax / Nukushi (Faksi)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='landline_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telephone / Simu'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postal Address / Anuani ya Posta'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='village_street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Village/Street / Kijiji au Mtaa'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ward / Kata'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Formal Education / Elimu (Rasmi)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax / Nukushi (Faksi)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='landline_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telephone / Simu'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_names',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Other Names / Majina Mengine'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postal Address / Anuani ya Posta'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='residency_duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Residency Duration / Muda wa Kuishi Mahali Hapo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surname / Jina la Ukoo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='village_street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Village/Street / Kijiji au Mtaa'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ward / Kata'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='country',
            field=models.CharField(default='Tanzania', max_length=100, verbose_name='Nationality / Country / Utaifa'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District / Wilaya'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='physical_address',
            field=models.TextField(blank=True, null=True, verbose_name='Physical Address'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region / Mkoa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Tanzania', max_length=100, verbose_name='Nationality / Country / Utaifa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District / Wilaya'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region / Mkoa'),
        ),
    ]
