# Generated by Django 5.0.14 on 2026-09-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_companyprofile_fax_companyprofile_landline_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='alternative_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alternative Contact'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alternative_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alternative Contact'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name'),
        ),
    ]
