# Generated by Django 5.0.14 on 2026-07-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeconfiguration',
            name='fee_type',
            field=models.CharField(choices=[('LISTING_APP_FEE', 'Listing of Traditional Medicines: 1. Ada ya maombi (Application fee)'), ('LISTING_EVAL_FEE', 'Listing of Traditional Medicines: 2. Ada ya tathmini (Evaluation fee)'), ('LISTING_FEE', 'Listing of Traditional Medicines: 3. Ada ya uorodheshaji (Listing fee)'), ('LISTING_RENEWAL_FEE', 'Listing of Traditional Medicines: 4. Ada ya kuhuisha (Renewal fee)'), ('LISTING_AMENDMENT_FEE', 'Listing of Traditional Medicines: 5. Ada ya marekebisho (Amendment fee)'), ('CAT_II_APP_FEE', 'Category II Traditional Medicines: 1. Ada ya maombi (Application fee)'), ('CAT_II_EVAL_FEE', 'Category II Traditional Medicines: 2. Ada ya tathmini (Evaluation fee)'), ('CAT_II_INSPECTION_FEE', 'Category II Traditional Medicines: 3. Ada ya ukaguzi wa uzalishaji (Manufacturing inspection fee)'), ('CAT_II_REGISTRATION_FEE', 'Category II Traditional Medicines: 4. Ada ya usajili (Registration fee)'), ('CAT_II_RENEWAL_FEE', 'Category II Traditional Medicines: 5. Ada ya kuhuisha (Renewal fee)'), ('CAT_II_AMENDMENT_FEE', 'Category II Traditional Medicines: 6. Ada ya marekebisho (Amendment fee)')], max_length=50, unique=True, verbose_name='Aina ya Ada (Fee Type)'),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='application_type',
            field=models.CharField(choices=[('LISTING', 'Listing of Traditional Medicines'), ('CATEGORY_II', 'Registration of Category II Traditional Medicines')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('LISTING_APP_FEE', 'Listing of Traditional Medicines: 1. Ada ya maombi (Application fee)'), ('LISTING_EVAL_FEE', 'Listing of Traditional Medicines: 2. Ada ya tathmini (Evaluation fee)'), ('LISTING_FEE', 'Listing of Traditional Medicines: 3. Ada ya uorodheshaji (Listing fee)'), ('LISTING_RENEWAL_FEE', 'Listing of Traditional Medicines: 4. Ada ya kuhuisha (Renewal fee)'), ('LISTING_AMENDMENT_FEE', 'Listing of Traditional Medicines: 5. Ada ya marekebisho (Amendment fee)'), ('CAT_II_APP_FEE', 'Category II Traditional Medicines: 1. Ada ya maombi (Application fee)'), ('CAT_II_EVAL_FEE', 'Category II Traditional Medicines: 2. Ada ya tathmini (Evaluation fee)'), ('CAT_II_INSPECTION_FEE', 'Category II Traditional Medicines: 3. Ada ya ukaguzi wa uzalishaji (Manufacturing inspection fee)'), ('CAT_II_REGISTRATION_FEE', 'Category II Traditional Medicines: 4. Ada ya usajili (Registration fee)'), ('CAT_II_RENEWAL_FEE', 'Category II Traditional Medicines: 5. Ada ya kuhuisha (Renewal fee)'), ('CAT_II_AMENDMENT_FEE', 'Category II Traditional Medicines: 6. Ada ya marekebisho (Amendment fee)')], max_length=50),
        ),
    ]
