# Generated by Django 5.0.14 on 2026-07-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_alter_feeconfiguration_fee_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineapplication',
            name='status',
            field=models.CharField(choices=[('PENDING_APPLICATION_FEE', 'Pending: Ada ya maombi (Application fee)'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted / Pending Review'), ('PENDING_EVALUATION_FEE', 'Pending: Ada ya tathmini (Evaluation fee)'), ('UNDER_REVIEW', 'Under Review'), ('PRELIMINARY_APPROVED', 'Preliminary Approved / Pending Scientific'), ('PENDING_INSPECTION_FEE', 'Pending: Ada ya ukaguzi wa uzalishaji (Manufacturing inspection fee)'), ('READY_FOR_INSPECTION', 'Ready for Inspection'), ('INSPECTION_COMPLETED', 'Inspection Completed / Pending Scientific'), ('PENDING_LISTING_FEE', 'Pending: Ada ya uorodheshaji (Listing fee)'), ('PENDING_REGISTRATION_FEE', 'Pending: Ada ya usajili (Registration fee)'), ('PENDING_FINAL_APPROVAL', 'Pending Final Approval'), ('PROVISIONAL_REGISTRATION', 'Provisional Registration'), ('FULL_REGISTRATION', 'Full Registration'), ('CONDITIONS_APPLIED', 'Conditions for Improvement'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
    ]
