# Generated by Django 5.0.14 on 2026-07-16 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_alter_medicineapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='control_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Control Number must be exactly 12 digits.', regex='^\\d{12}$')], verbose_name='Control Number'),
        ),
    ]
