# Generated by Django 5.0.14 on 2026-07-16 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_remove_payment_receipt_number_payment_control_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Receipt Number must be exactly 15 digits.', regex='^\\d{15}$')], verbose_name='Receipt Number'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Reference Number must be exactly 16 characters.', regex='^.{16}$')], verbose_name='Reference Number'),
        ),
    ]
