# Generated by Django 5.0.14 on 2026-09-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_payment_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineapplication',
            name='traditional_medicine_skills_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Taja ujuzi mwingine (Specify Other)'),
        ),
    ]
