# Generated by Django 5.0.14 on 2026-09-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0009_medicineapplication_traditional_medicine_skills_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineapplication',
            name='skills_acquired_details',
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='inherited_duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Muda uliojifunza'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='inherited_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Taja jina la fundi / mtu uliyemrithi'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='training_duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Muda wa mafunzo'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='training_institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Taja Taasisi ya Mafunzo / Mganga wa Tiba Asili'),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='traditional_medicine_skills',
            field=models.CharField(blank=True, choices=[('MAFUNZO', 'Mafunzo rasmi'), ('KURITHI', 'Kurithi'), ('MENGINEYO', 'Mengineyo')], max_length=20, null=True, verbose_name='Ulipataje ujuzi katika tiba asili?'),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='traditional_medicine_skills_other',
            field=models.TextField(blank=True, null=True, verbose_name='Mengineyo; eleza'),
        ),
    ]
