# Generated by Django 5.0.14 on 2026-09-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0010_remove_medicineapplication_skills_acquired_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineapplication',
            name='inherited_duration_type',
            field=models.CharField(blank=True, choices=[('YEARS', 'Miaka (Years)'), ('MONTHS', 'Miezi (Months)'), ('WEEKS', 'Majuma (Weeks)'), ('DAYS', 'Siku (Days)')], max_length=20, null=True, verbose_name='Aina ya muda'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='training_duration_type',
            field=models.CharField(blank=True, choices=[('YEARS', 'Miaka (Years)'), ('MONTHS', 'Miezi (Months)'), ('WEEKS', 'Majuma (Weeks)'), ('DAYS', 'Siku (Days)')], max_length=20, null=True, verbose_name='Aina ya muda'),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='inherited_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Muda uliojifunza'),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='training_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Muda wa mafunzo'),
        ),
    ]
