# Generated by Django 5.0.14 on 2026-09-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0011_medicineapplication_inherited_duration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineapplication',
            name='dosage_form',
            field=models.CharField(choices=[('KIMIMINIKA', 'Kimiminika'), ('UNGA', 'Unga'), ('VIDONGE', 'Vidonge'), ('MENGINEYO', 'Mengineyo')], max_length=100, verbose_name='Hali ya dawa (Dosage form)'),
        ),
    ]
