# Generated by Django 5.0.14 on 2026-09-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0012_alter_medicineapplication_dosage_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineapplication',
            name='dosage_form_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Taja Hali ya dawa'),
        ),
    ]
