# Generated by Django 5.0.14 on 2026-09-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0013_medicineapplication_dosage_form_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineapplication',
            name='drying_procedures',
        ),
        migrations.RemoveField(
            model_name='medicineapplication',
            name='imported_abundance',
        ),
        migrations.RemoveField(
            model_name='medicineapplication',
            name='imported_countries',
        ),
        migrations.RemoveField(
            model_name='medicineapplication',
            name='imported_plant_part',
        ),
        migrations.RemoveField(
            model_name='medicineapplication',
            name='imported_raw_state',
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='does_dry_raw_materials',
            field=models.BooleanField(default=False, verbose_name='Je, una kausha dawa ghafi?'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='known_side_effects',
            field=models.BooleanField(default=False, verbose_name='Je, dawa ina madhara yanayojulikana?'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='local_harvested_part_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sehemu nyingine'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='net_weight_volume_unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('mL', 'mL')], max_length=10, null=True, verbose_name='Kipimo'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='route_of_administration_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Njia nyingine'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='storage_conditions_other',
            field=models.TextField(blank=True, null=True, verbose_name='Iwapo mazingira maalum, elezea:'),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='dosage_form',
            field=models.CharField(choices=[('UNGA', 'Unga'), ('KIMIMINIKA', 'Kimiminika'), ('KIDONGE', 'Kidonge'), ('CAPSULE', 'Capsule'), ('NYINGINE', 'Nyingine')], max_length=100, verbose_name='Hali ya dawa (Dosage form)'),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='local_abundance',
            field=models.CharField(blank=True, choices=[('KUBWA_SANA', 'Upatikanaji mkubwa sana'), ('KUBWA', 'Upatikanaji mkubwa'), ('KAWAIDA', 'Upatikanaji wa kawaida'), ('MDOGO', 'Upatikanaji mdogo'), ('MDOGO_SANA', 'Upatikanaji mdogo sana')], max_length=50, null=True, verbose_name='Hali ya upatikanaji (Local)'),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='local_harvest_season',
            field=models.CharField(blank=True, choices=[('KIANGAZI', 'Kiangazi'), ('MASIKA', 'Masika'), ('VULI', 'Vuli'), ('KIPUPWE', 'Kipupwe')], max_length=50, null=True, verbose_name='Msimu wa kuvuna (Local)'),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='local_harvested_part',
            field=models.CharField(blank=True, choices=[('MAJANI', 'Majani'), ('MIZIZI', 'Mizizi'), ('MAGOME', 'Magome'), ('MATUNDA', 'Matunda'), ('MAUA', 'Maua'), ('UTOMVU', 'Utomvu'), ('MENGINEYO', 'Mengineyo')], max_length=50, null=True, verbose_name='Sehemu inayovunwa (Local)'),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='route_of_administration',
            field=models.CharField(blank=True, choices=[('KUPAKA', 'Kupaka'), ('KUNYWA', 'Kunywa'), ('KUVUTA', 'Kuvuta'), ('KUFUKIZA', 'Kufukiza'), ('KUSUKUTUA', 'Kusukutua'), ('NYINGINE', 'Njia nyingine')], max_length=50, null=True, verbose_name='Namna ya utoaji wa dawa (Route of administration)'),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='storage_conditions',
            field=models.CharField(choices=[('JOTO_LA_KAWAIDA', 'Joto la kawaida (Room Temperature)'), ('MAZINGIRA_MAALUM', 'Mazingira maalum')], default='JOTO_LA_KAWAIDA', max_length=50, verbose_name='Storage conditions (Masharti ya utunzaji)'),
        ),
    ]
