# Generated by Django 5.0.14 on 2026-09-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0014_remove_medicineapplication_drying_procedures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineapplication',
            name='net_weight_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kiasi (Net Weight/Net Volume)'),
        ),
    ]
