# Generated by Django 5.0.14 on 2026-09-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0015_alter_medicineapplication_net_weight_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineapplication',
            name='shelf_life_duration_type',
            field=models.CharField(blank=True, choices=[('MIAKA', 'Miaka'), ('MIEZI', 'Miezi'), ('MAJUMA', 'Majuma'), ('SIKU', 'Siku')], max_length=20, null=True, verbose_name='Aina ya muda (Shelf life)'),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='shelf_life',
            field=models.IntegerField(blank=True, null=True, verbose_name='Muda wa matumizi wa dawa (Shelf life)'),
        ),
    ]
