# Generated by Django 5.0.14 on 2026-09-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0016_medicineapplication_shelf_life_duration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineapplication',
            name='shelf_life_duration_type',
            field=models.CharField(blank=True, choices=[('YEARS', 'Miaka (Years)'), ('MONTHS', 'Miezi (Months)'), ('WEEKS', 'Majuma (Weeks)'), ('DAYS', 'Siku (Days)')], max_length=20, null=True, verbose_name='Aina ya muda (Shelf life)'),
        ),
    ]
