# Generated by Django 5.0.14 on 2026-09-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0017_alter_medicineapplication_shelf_life_duration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineapplication',
            name='empty_packaging_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ujazo wa kifungashio kabla ya kuweka dawa'),
        ),
    ]
