# Generated by Django 5.0.14 on 2026-09-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0018_medicineapplication_empty_packaging_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineapplication',
            name='other_appearance_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Maelekezo mengine'),
        ),
    ]
