# Generated by Django 5.0.14 on 2026-09-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0019_alter_medicineapplication_other_appearance_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineapplication',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of raw materials or herbs used', null=True, verbose_name='Medicine ingredients information (Taarifa za viambato vya dawa)'),
        ),
    ]
