# Generated by Django 5.0.14 on 2026-09-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0020_alter_medicineapplication_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineapplication',
            name='manufacturing_area_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saizi ya eneo/jengo'),
        ),
    ]
