# Generated by Django 5.0.14 on 2026-09-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0021_alter_medicineapplication_manufacturing_area_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineapplication',
            name='foreign_source_countries',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nchi zinakotoka (Countries of origin)'),
        ),
    ]
