# Generated by Django 5.0.14 on 2026-09-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0022_medicineapplication_foreign_source_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineapplication',
            name='foreign_abundance',
            field=models.CharField(blank=True, choices=[('KUBWA_SANA', 'Upatikanaji mkubwa sana'), ('KUBWA', 'Upatikanaji mkubwa'), ('KAWAIDA', 'Upatikanaji wa kawaida'), ('MDOGO', 'Upatikanaji mdogo'), ('MDOGO_SANA', 'Upatikanaji mdogo sana')], max_length=50, null=True, verbose_name='Hali ya upatikanaji (Foreign)'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='foreign_cultivated_or_wild',
            field=models.CharField(blank=True, choices=[('INALIMWA', 'Inalimwa (Cultivated)'), ('ASILI', 'Za Asili (Wild)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='foreign_harvest_season',
            field=models.CharField(blank=True, choices=[('KIANGAZI', 'Kiangazi'), ('MASIKA', 'Masika'), ('VULI', 'Vuli'), ('KIPUPWE', 'Kipupwe')], max_length=50, null=True, verbose_name='Msimu wa kuvuna (Foreign)'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='foreign_harvested_part',
            field=models.CharField(blank=True, choices=[('MAJANI', 'Majani'), ('MIZIZI', 'Mizizi'), ('MAGOME', 'Magome'), ('MATUNDA', 'Matunda'), ('MAUA', 'Maua'), ('UTOMVU', 'Utomvu'), ('MENGINEYO', 'Mengineyo')], max_length=50, null=True, verbose_name='Sehemu inayovunwa (Foreign)'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='foreign_harvested_part_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sehemu nyingine (Foreign)'),
        ),
    ]
