# Generated by Django 5.0.14 on 2026-09-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0023_medicineapplication_foreign_abundance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineapplication',
            name='storage_environment',
            field=models.TextField(blank=True, null=True, verbose_name='Mazingira ya utunzaji dawa iliyokwisha tengenezwa'),
        ),
    ]
