# Generated by Django 5.0.14 on 2026-09-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0024_medicineapplication_storage_environment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineapplication',
            name='dosage',
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='dosage_frequency',
            field=models.CharField(blank=True, choices=[('MARA_1', 'Kutwa mara 1 (Once a day)'), ('MARA_2', 'Kutwa mara 2 (Twice a day)'), ('MARA_3', 'Kutwa mara 3 (Three times a day)'), ('MARA_4', 'Kutwa mara 4 (Four times a day)'), ('KILA_BAADA_MASAA_8', 'Kila baada ya masaa 8 (Every 8 hours)'), ('KILA_BAADA_MASAA_12', 'Kila baada ya masaa 12 (Every 12 hours)'), ('KAMA_INAVYOHITAJIKA', 'Kama inavyohitajika (As needed / PRN)')], max_length=50, null=True, verbose_name='Muda wa matumizi (Frequency)'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='dosage_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Kiasi cha kipimo (Quantity)'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='dosage_unit',
            field=models.CharField(blank=True, choices=[('VIDONGE', 'Vidonge (Tablets/Capsules)'), ('VIJIKO', 'Vijiko (Spoons)'), ('ML', 'Mililita (ml)'), ('MG', 'Miligramu (mg)'), ('G', 'Gramu (g)'), ('LITA', 'Lita (Liters)'), ('MENGINEYO', 'Mengineyo (Other)')], max_length=50, null=True, verbose_name='Kipimo (Unit)'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('SIKU', 'Siku (Days)'), ('WIKI', 'Wiki (Weeks)'), ('MIEZI', 'Miezi (Months)')], max_length=50, null=True, verbose_name='Aina ya muda (Duration Unit)'),
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='duration_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idadi ya muda (Duration Value)'),
        ),
    ]
