# Generated by Django 5.0.14 on 2026-09-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0025_remove_medicineapplication_dosage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineapplication',
            name='dosage_frequency',
        ),
        migrations.RemoveField(
            model_name='medicineapplication',
            name='dosage_quantity',
        ),
        migrations.RemoveField(
            model_name='medicineapplication',
            name='dosage_unit',
        ),
        migrations.RemoveField(
            model_name='medicineapplication',
            name='duration_unit',
        ),
        migrations.RemoveField(
            model_name='medicineapplication',
            name='duration_value',
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='dosage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kipimo cha matumizi (Dosage)'),
        ),
    ]
