# Generated by Django 5.0.14 on 2026-09-20 22:46

import core.utils.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0026_remove_medicineapplication_dosage_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineapplication',
            name='sample_label',
        ),
        migrations.CreateModel(
            name='MedicineLabelAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.utils.uploads.medicine_document_path, verbose_name='Sample medicine label attachment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_attachments', to='medicines.medicineapplication')),
            ],
        ),
    ]
