# Generated by Django 5.0.14 on 2026-09-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0027_remove_medicineapplication_sample_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineapplication',
            name='instructions_for_use',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Instructions for use (Maelekezo ya matumizi)'),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='possible_side_effects',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Possible side effects (Madhara yanayoweza kutokea)'),
        ),
    ]
